'''34. Write a program that creates an iterator to print squares of numbers'''
class Square():
    def __iter__(self):
        self.num=int(input("Enter a Number : "))
        return self
    def __next__(self):
        x=self.num
        self.num=x**2
        return self.num
        
myclass=Square()
myiter=iter(myclass)
print("The Square of entered Number Generated by Iterator---->>>>",next(myiter))